SELECT S.ROUTE, CONCAT(ROUND(SUM(S.D_BETWEEN_DIST), 2), 'km') as TOTAL_DISTANCE, CONCAT(ROUND(AVG(S.D_BETWEEN_DIST), 3), 'km') as AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE S
GROUP BY ROUTE
ORDER BY TOTAL_DISTANCE DESC
