SELECT B.BOOK_ID BOOK_ID, A.AUTHOR_NAME AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE 
FROM BOOK B, AUTHOR A
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND B.CATEGORY = "경제"
ORDER BY B.PUBLISHED_DATE ASC;
